### ISSUE TITLE
error log when running node `GetTypes.js`

### ISSUE THREAD

**Issue by ubb6616** [DeepTyper/DeepTyper#10]
Hi,

I wonder whether this output error is normal as `node GetTypes.js` indeed creates the three output data dorectories but output this error, would this error causes any unexpected problems?

![image](https://user-images.githubusercontent.com/129969095/230286587-3d19fb4e-2647-4725-94f6-42ecdf7deb70.png)

Regards,

**Comment by VHellendoorn** [comment]
Hi, no I don't remember seeing this error. Perhaps it's a compatibility issue with a more recent version of TypeScript? As I mentioned previously, this code is really quite old by now. TypeScript has changed in major ways in the past five years and DeepTyper is quite far from the state-of-the-art at this point, so I strongly suggest working with code from more recent publications in this space.
