### ISSUE TITLE
TypeScript version

### ISSUE THREAD

**Issue by ubb6616** [DeepTyper/DeepTyper#11]
Hi,

Is it convenient for you to share which TypeScript version you use?

Regards,

**Comment by VHellendoorn** [comment]
I'm afraid I don't have access to the original source code anymore. If this is in relation to the error in #10, perhaps it'd be easiest to build in exception handling and skip files where such errors occur? If it's quite rare, it should be fine to ignore those. If it is common, it might be worth pulling a TS compiler from ~4-5 years ago (starting from 3.0 and down to 2.2 -- I'm guessing I used 2.4 which came out in June 2017) to run the code with.

**Comment by ubb6616** [comment]
OK. I will try a different compiler version then. Thanks.
