### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by amilajack** [DeepTyper/DeepTyper#2]
I am confused on what the steps are to use this project on a js file. How can I use a pretrained model and use that model to infer types of a JS file?

**Comment by VHellendoorn** [comment]
Hi, good question, the code to do so is part of the web API that is not yet released. As a first approximation, check the `run_seq` method in evaluation.py. Basically the process is to use a lexer (like Pygments) to lex the JS/TS code, convert it to a numpy array with one-hot vectors and ask the model to `eval` the output with respect to the input. I will upload code to do this as soon as possible.
