### ISSUE TITLE
error on run "infer.py"

### ISSUE THREAD

**Issue by llnlln** [DeepTyper/DeepTyper#3]
Hi @VHellendoorn ,

The following error occurred when running `infer.py`

![train](https://user-images.githubusercontent.com/32690972/55382023-2a32d180-5557-11e9-98ee-babd7910e2eb.png)

Could you tell me what is your GPU environment?

**Comment by VHellendoorn** [comment]
Hi there,

This error suggest that your video card cannot fit the full batch in memory. Your screenshot doesn't show me which GPU you are using, but I suspect it has a smaller memory than the (1080ti) one we used. Try reducing your minibatch size; it should not affect training performance by much.

-Vincent
