### ISSUE TITLE
A trained model

### ISSUE THREAD

**Issue by izosak** [DeepTyper/DeepTyper#4]
Hi,

First of all I would like to thank you for sharing this valuable project with us. The uses of this tool are surely going to be very helpful for the whole programming community.

Second, may I ask if you still possess a trained model (one of those created by `infer.py`), and if so, is it possible to ask that you share it with us? Unfortunately I have some hardware limitations that don't allow me to train the model by myself.

Such help would be much appreciated.

**Comment by VHellendoorn** [comment]
Hi, 

Good question; I couldn't find the original model, so I am retraining one now. Should push by the afternoon (pacific time). I will also include some python code that can read JavaScript/TypeScript from a file and, using the pre-trained model and vocabularies, produces the types inferred for each token.

-Vincent

**Comment by VHellendoorn** [comment]
Hi again, I ran into the ridiculous file size limits that Github imposes (the model is more than 100MB). I will upload it on some file sharing service tomorrow and push the data then.
-Vincent

**Comment by VHellendoorn** [comment]
Closed in 66098a8
