### ISSUE TITLE
txt2ctf.py is missing

### ISSUE THREAD

**Issue by michaelpradel** [DeepTyper/DeepTyper#7]
Thanks for sharing the implementation of DeepTyper!

Following the instructions in the README, the txt2ctf.py script is missing. I used the one from https://github.com/microsoft/CNTK/blob/master/Scripts/txt2ctf.py, which seems to work well. You may want to add this script to the repository, to avoid confusing others.

**Comment by VHellendoorn** [comment]
Thanks for letting me know! I decided to add the link to CNTK's repo version in the README.

From a more general perspective, now that CNTK is no longer updating, it is probably time to deprecate this repository as well. If you are using it for research baselining purposes relative to specifically the published paper's version, I imagine it can continue to be used as is for quite some time into the future. However, if your goal is to leverage a strong ML baseline, I encourage you to either consider [LambdaNet](https://openreview.net/forum?id=Hkx6hANtwH), or let me know if there is interest in a Tensorflow-compatible, and all-around substantially modernized, version (based on Transformers & utilizing BPE) instead; I'm happy to share such an implementation.

**Comment by FeldiPat** [comment]
Hey Vincent,

I would be very interested in a TensorFlow-compatible implementation for some experimenting.

Greetings
Patric
