### ISSUE TITLE
question about data normalization

### ISSUE THREAD

**Issue by ubb6616** [DeepTyper/DeepTyper#9]
Hi,

Thanks for the great work. We notice that the following data preprocessing would weirdly normalize identifiers into "0" as well (as shown in Figure 2).

![image](https://user-images.githubusercontent.com/129969095/230106455-b568a719-3e33-4cac-b52c-3d5bf0f6ce21.png)

![6ad2475f9ac0787eba6249794ab750c](https://user-images.githubusercontent.com/129969095/230106845-43e6f886-7373-4bf7-ae92-0e867025b3e3.png)

Thanks

**Comment by VHellendoorn** [comment]
Good catch! I bet that slightly reduced our model's performance. Fortunately, many stronger models have come out since then that (I bet) don't suffer from these limitations.
